
#define MOVEMENT_SPEED 500
#define SCREEN_WIDTH 1000
#define SCREEN_HEIGHT 750
#define PLAYER_WIDTH 44
#define PLAYER_HEIGHT 20
#define ENEMY_WIDTH 44
#define ENEMY_HEIGHT 32
#define BULLET_WIDTH 6
#define BULLET_HEIGHT 14
#define BUNKER_WIDTH 150
#define BUNKER_HEIGHT 6
#define BUNKER_HP 3
